version: '3.4'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo
    restart: always
    volumes:
      - ./volumes/MongoDB:/data/db

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    depends_on:
      - mongo