version: '3.3'
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    ports:
      - 27017:27017
    volumes:
      - ../volumes/MongoDB:/data/db
    networks:
      - mongo-compose-network

networks:
 mongo-compose-network:
   driver: bridge